"""
database/generate_large_dag.py
-------------------------------
Generates a synthetic DAG with 1000+ nodes and 1500+ edges
for performance and stress testing the lineage system.

Usage:
    python generate_large_dag.py
    # Outputs: large_dag.json (upload this via the UI or API)
"""

import json
import random
import math
from datetime import datetime

random.seed(42)  # reproducibility

OPERATIONS = ["filter", "join", "aggregation", "projection", "sort", "deduplicate", "union", "custom"]
TYPES = ["source", "transformation", "sink"]

def generate_large_dag(
    n_sources=50,
    n_transforms_per_layer=80,
    n_layers=8,
    n_sinks=40,
    branching_factor=2,
) -> dict:
    """
    Generates a layered DAG:
      Layer 0: source nodes
      Layers 1..n_layers: transformation nodes
      Last layer: sink nodes

    Each node in layer i receives edges from 1–branching_factor
    randomly selected nodes in layer i-1.
    This ensures the graph is acyclic by construction.
    """
    nodes = []
    edges = []
    layers = []

    # ── Source nodes (Layer 0) ────────────────────────────────────────
    source_ids = []
    for i in range(n_sources):
        node_id = f"src_{i:03d}"
        nodes.append({
            "id": node_id,
            "name": f"Source {i} ({random.choice(['S3', 'Kafka', 'RDBMS', 'API'])})",
            "type": "source",
            "tags": [random.choice(["batch", "streaming", "cdc"])],
            "version": f"v{random.randint(1,5)}.{random.randint(0,9)}",
        })
        source_ids.append(node_id)
    layers.append(source_ids)

    # ── Transformation layers ─────────────────────────────────────────
    for layer_idx in range(1, n_layers + 1):
        prev_layer = layers[layer_idx - 1]
        layer_ids = []
        for j in range(n_transforms_per_layer):
            node_id = f"t{layer_idx}_{j:04d}"
            operation = random.choice(OPERATIONS)
            nodes.append({
                "id": node_id,
                "name": f"L{layer_idx} {operation.title()} {j}",
                "type": "transformation",
                "operation": operation,
                "description": f"Layer {layer_idx} transformation step {j}",
            })
            layer_ids.append(node_id)

            # Connect from 1–branching_factor nodes in previous layer
            n_parents = random.randint(1, min(branching_factor, len(prev_layer)))
            parents = random.sample(prev_layer, n_parents)
            for parent in parents:
                edges.append({
                    "from": parent,
                    "to": node_id,
                    "relationship_type": operation,
                })

        layers.append(layer_ids)

    # ── Sink nodes (final layer) ──────────────────────────────────────
    last_transform_layer = layers[-1]
    sink_types = ["Data Warehouse", "Dashboard", "Feature Store", "ML Model", "Data Lake", "API"]
    for k in range(n_sinks):
        node_id = f"sink_{k:03d}"
        nodes.append({
            "id": node_id,
            "name": f"{random.choice(sink_types)} {k}",
            "type": "sink",
            "description": f"Output sink {k}",
            "tags": [random.choice(["redshift", "tableau", "feast", "s3", "kafka"])],
        })

        # Each sink connects from 1–3 final transform nodes
        n_parents = random.randint(1, min(3, len(last_transform_layer)))
        parents = random.sample(last_transform_layer, n_parents)
        for parent in parents:
            edges.append({
                "from": parent,
                "to": node_id,
                "relationship_type": "written_to",
            })

    # Deduplicate edges (same from→to can be generated by coincidence)
    seen_edges = set()
    unique_edges = []
    for edge in edges:
        key = (edge["from"], edge["to"])
        if key not in seen_edges:
            seen_edges.add(key)
            unique_edges.append(edge)

    dag = {
        "name": f"Large Performance Test DAG ({len(nodes)} nodes)",
        "description": (
            f"Synthetic DAG generated for performance testing. "
            f"{n_layers} transform layers, {n_sources} sources, {n_sinks} sinks."
        ),
        "version": 1,
        "nodes": nodes,
        "edges": unique_edges,
    }

    return dag


if __name__ == "__main__":
    dag = generate_large_dag(
        n_sources=50,
        n_transforms_per_layer=100,
        n_layers=8,
        n_sinks=50,
        branching_factor=3,
    )

    filename = "large_dag.json"
    with open(filename, "w") as f:
        json.dump(dag, f, indent=2)

    print(f"✅ Generated large DAG:")
    print(f"   Nodes : {len(dag['nodes'])}")
    print(f"   Edges : {len(dag['edges'])}")
    print(f"   Output: {filename}")
    print(f"\nTo test: POST this file to /api/v1/upload-dag/file")
